### ISSUE TITLE
Add title for the overall json schema

### ISSUE THREAD

**Issue by braghettos** [krateoplatformops/crdgen#32]
The expected result is the following:

```
spec:
  versions:
  - schema:
      openAPIV3Schema:
        description: Description of the form
        title: Title of the form
```
